spring.application.name=IETI-11
spring.data.mongodb.uri = mongodb+srv://admin_ieti13:admin1234@ieti13.1dqwkwu.mongodb.net/IETI-11?retryWrites=true&w=majority&appName=ieti13
#spring.datasource.url=jdbc:postgresql://localhost:5432/ieti_11
#spring.datasource.username=admin_ieti11
#spring.datasource.password=admin1234
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
