spring.application.name=IETI-11
spring.datasource.url=jdbc:postgresql://localhost:5432/ieti_11
spring.datasource.username=admin_ieti11
spring.datasource.password=admin1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

